---
- name: Deploy monitoring stack
  hosts: localhost
  become: true
  roles:
    - prerequisites
    - monitoring_stack
    - k3s

- name: Register monitoring DNS in Pi-hole
  hosts: localhost
  become: false
  roles:
    - pihole_dns
